# resolver: lts-11.22
resolver: lts-12.14

packages:
- '.'
- location: ../shmm
  extra-dep: true
- location: ../smol
  extra-dep: true

extra-deps: 
- eigen-3.3.4.1
- containers-0.5.11.0
- gamma-0.9.0.2
- normaldistribution-1.1.0.3
- continued-fractions-0.9.1.1
- converge-0.1.0.1


flags: {}

extra-package-dbs: []

nix:
  packages: [eigen3_3, pkgconfig, cairo, zlib, gmp, ncurses, gcc, ihaskell]
