# resolver: lts-11.22
resolver: lts-9.12

packages:
- '.'
- location: ../shmm
  extra-dep: true
- location: ../smol
  extra-dep: true

extra-deps: 
# - sparse-lin-alg-0.4.3
#- vector-0.12.0.0
- eigen-3.3.4.1
- containers-0.5.11.0
#- containers-0.5.8.1

flags: {}

extra-package-dbs: []

nix:
  packages: [eigen3_3, pkgconfig, cairo, zlib, gmp, ncurses, gcc]
